###
GET http://localhost:8080/ HTTP/1.1
###
POST http://localhost:3000/user/email HTTP/1.1
Content-Type: application/json

{
    "email": "sophia5460@naver.com"
}
###
POST http://localhost:3000/user/register HTTP/1.1
Content-Type: application/json

{
    "uid":"dd",
    "pw":"dd",
    "name" :"dd",
    "email": "sophia5460@naver.com"
}

###
POST http://localhost:3000/user/login HTTP/1.1
Content-Type: application/json

{
    "uid":"dd",
    "pw":"dd"
}
###
POST http://localhost:3000/cp/img HTTP/1.1
Content-Type: application/json

{
    "email": "sophia5460@naver.com"
}